version: '3.4'

services:
  secondary-cron-uk-v1:
    logging:
      driver: journald
    image: 824775819187.dkr.ecr.eu-west-2.amazonaws.com/secondary-cron-uk-v1:latest
    container_name: secondary-cron-uk-v1
    restart: unless-stopped
    environment:
      - CAM_URL=https://forapi.chameleonerp.co.uk
      - CAM_DB=liveerp
      - CAM_USERNAME=admin
      - CAM_PASSWORD=b1ackcat.73
      - SC_UK_V1_UPDATE_WAIT_SEC=60
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
