AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  ERP UK v1 Secondary Cron

Globals:
  Function:
    Timeout: 3

Resources:
  QuickESOProcessFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: quick_eso_processor.lambda_handler
      Runtime: python3.11
      Timeout: 900
      Architectures:
        - x86_64
      Events:
        QuickESOProcessScheduleRule:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "secretsmanager:GetSecretValue"
              Resource: "*"

  JobOrderMessengerToday:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: job_order_messenger_today.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        JobOrderMessengerTodayScheduleRule:
          Type: Schedule
          Properties:
            Schedule: cron(00 7 * * ? *)

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "secretsmanager:GetSecretValue"
              Resource: "*"

  JobOrderMessenger48hrs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: job_order_messenger_48hrs.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        JobOrderMessenger48hrsScheduleRule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "secretsmanager:GetSecretValue"
              Resource: "*"

  JobOrderMessenger24hrs:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: job_order_messenger_24hrs.lambda_handler
      Runtime: python3.11
      Timeout: 300
      Architectures:
        - x86_64
      Events:
        JobOrderMessenger24hrsScheduleRule:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)

      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "secretsmanager:GetSecretValue"
              Resource: "*"
