name: Publish Docker Image
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: Change to workspace
        run: |
          cd ${{ github.workspace }}
      - name: Run the publish.sh
        run: |
          ./publish.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
