name: Publish Docker Image
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
jobs:
  publish:
    runs-on: self-hosted
    steps:
      - run: echo "Image Publish"
      - name: Checkout Repository Code
        uses: actions/checkout@master
      - name: Change to workspace
        run: |
          cd ${{ github.workspace }}
      - name: Run the publish.sh
        run: |
          ./publish.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
  deploy:
    runs-on: self-hosted
    needs: publish
    steps:
      - run: echo "Deploy"
      - name: Checkout Repository Code
        uses: actions/checkout@master
      - name: Change to workspace
        run: |
          cd ${{ github.workspace }}
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i 3.10.196.41, ansible.yml
      - run: echo "🍏 This job's status is ${{ job.status }}."